###

POST https://localhost:5001/api/LoginInfos/SignUp HTTP/1.1
content-type: application/json

 {
     "emailId": "erabxes@gmail.com",
     "username": "erabxes",
     "password": "12345",
     "confirmPassword": "12345"
 }

###
GET https://localhost:5001/api/LoginInfos/GetLoginInfo/erabxes HTTP/1.1
###
GET https://localhost:5001/api/LoginInfos/GetLoginInfoById/Kr8hHoKNWUOAAVWxEVXw+g== HTTP/1.1
###
POST http://3.23.105.25/Airopay/security/tokenize HTTP/1.1
Content-Type: text/plain
    grant_type=password&username=AiroPay&password=L@g0s123$%

###